# Generated by Django 3.1.1 on 2020-10-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20201029_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='nick',
            new_name='nickname',
        ),
    ]
